City-of-Helsinki/linkedregistrations-ui

README.md, public/locales/en/enrolment.json, public/locales/fi/enrolment.json, public/locales/sv/enrolment.json, src/domain/enrolment/EnrolmentCompletedPage.tsx, src/domain/enrolment/__tests__/EnrolmentCompletedPage.test.tsx, src/domain/enrolment/constants.ts, src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
Automatically redirect user to redirect_url after successful enrolment
[LINK-775](https://helsinkisolutionoffice.atlassian.net/browse/LINK-775)
=> LINK-775 | Automatically redirect user to redirect_url after successful enrolment

README.md, jest.config.js, src/domain/app/layout/pageLayout/PageLayout.tsx, src/domain/app/layout/pageLayout/__tests__/PageLayout.test.tsx, src/domain/app/layout/pageLayout/pageLayout.module.scss, src/domain/enrolment/constants.ts, src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx, yarn.lock
Embedded version of the enrolment form
[LINK-759](https://helsinkisolutionoffice.atlassian.net/browse/LINK-759)
=> LINK-759 | Embedded version of enrolment form

src/common/components/formFields/__tests__/CheckboxGroupField.test.tsx, src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx, src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx, src/domain/enrolment/modals/confirmCancelModal/__tests__/ConfirmCancelModal.test.tsx, src/domain/enrolment/summaryPage/__tests__/SummaryPage.test.tsx
Improve performance of unit tests
[LINK-1078](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1078)
=> LINK-1078 | Unit test performance improvements

Dockerfile, azure-pipelines-dev.yml, docker-compose.yml, next.config.js
Fix docker build
[LINK-1116](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1116)
[LINK-1116]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1116 | Fix docker build

azure-pipelines-build-prod.yml
**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**
=> Changed prod pipeline pool to Production

src/pages/_app.tsx
Increase session refetch interval to 5 minutes to avoid re-rendering page all the time
[LINK-1439](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1439)
[LINK-1439]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1439 | Increase session refetch interval

public/locales/en/common.json, public/locales/fi/common.json, public/locales/sv/common.json, src/common/components/buttonPanel/ButtonPanel.tsx, src/common/components/buttonPanel/buttonPanel.module.scss, src/common/components/serverErrorSummary/ServerErrorSummary.tsx, src/domain/app/header/Header.tsx, src/domain/app/header/__tests__/Header.test.tsx, src/domain/signupGroup/summaryPage/SummaryPage.tsx, src/domain/signupGroup/summaryPage/__tests__/SummaryPage.test.tsx
Move back button to bottom of the summary page
[LINK-1514](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1514)
[LINK-1514]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1514 | Move back button to bottom of the summary page

src/domain/signupGroup/registrationWarning/RegistrationWarning.tsx, src/domain/signupGroup/signupGroupForm/availableSeatsText/AvailableSeatsText.tsx, src/domain/signupGroup/signupGroupForm/availableSeatsText/SeatsCount.tsx, src/domain/signupGroup/signupGroupForm/availableSeatsText/__tests__/AvailableSeatsText.test.tsx
Lazy load available seats amount to avoid conflict between client and server
[LINK-1501](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1501)
[LINK-1501]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1501 | Lazy load available seats amount

package.json, src/domain/app/axios/axiosClient.ts, yarn.lock
Add logging for the axios requests and responses. Log only requests and responses in the server side.
[LINK-1624](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1624)
[LINK-1624]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1624 | Log Axios requests and responses

public/locales/en/signup.json, public/locales/fi/signup.json, src/domain/signupGroup/__tests__/SignupGroupCompletedPage.test.tsx, src/domain/signupGroup/participantAmountSelector/__tests__/ParticipantAmountSelector.test.tsx, src/domain/signupGroup/reservationTimer/__tests__/ReservationTimer.test.tsx, src/domain/signupGroup/summaryPage/signups/signup/__tests__/Signup.test.tsx
Replace term "varasija" with "jono"
[LINK-1636](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1636)
[LINK-1636]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1636 | Replace term "varasija" with "jono"

.vscode/settings.json, public/locales/en/signup.json, public/locales/fi/signup.json, public/locales/sv/signup.json
Update data protection link address
[LINK-1730](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1730)
[LINK-1730]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1730 | Update data protection link address

src/domain/app/header/Header.tsx, src/domain/app/header/__tests__/Header.test.tsx, src/domain/signInRequired/SignInRequired.tsx, src/domain/signInRequired/__tests__/SignInRequired.test.tsx, src/domain/signupGroup/authenticationRequiredNotification/AuthenticationRequiredNotification.tsx, src/domain/signupGroup/authenticationRequiredNotification/__tests__/AuthenticationRequiredNotification.test.tsx, src/hooks/useSignIn.ts
Add ui_locales parameter to Keycloak url so the selected language is used also in the authentication service
=> fix: use selected language in login

public/locales/en/summary.json, public/locales/fi/summary.json, public/locales/sv/summary.json, src/common/components/splittedRow/SplittedRow.tsx, src/common/components/splittedRow/splittedRow.module.scss, src/constants.ts, src/domain/registration/__mocks__/registration.ts, src/domain/signup/__mocks__/signup.ts, src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx, src/domain/signupGroup/__tests__/validation.test.ts, src/domain/signupGroup/signupGroupForm/signups/signup/Signup.tsx, src/domain/signupGroup/signupGroupForm/signups/signup/__tests__/Signup.test.tsx, src/domain/signupGroup/signupGroupForm/signups/signup/signup.module.scss, src/domain/signupGroup/summaryPage/signups/signup/Signup.tsx, src/domain/signupGroup/summaryPage/signups/signup/__tests__/Signup.test.tsx, src/domain/signupGroup/summaryPage/signups/signup/signup.module.scss, src/domain/signupGroup/testUtils.ts, src/domain/signupGroup/validation.ts
We want to collect data only for the mandatory fields so hide all the signup fields which are not set to be mandatory
[LINK-1805](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1805)
[LINK-1805]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1805 | Display only mandatory signup fields

azure-pipelines-acceptance-tests.yml, azure-pipelines-build-dev.yml, azure-pipelines-build-prod.yml, azure-pipelines-build-staging.yml, azure-pipelines-build-test.yml, pipelines/linkedregistrations-ui-dev.yml, pipelines/linkedregistrations-ui-release.yml, pipelines/linkedregistrations-ui-review.yml
**[OH-35](https://helsinkisolutionoffice.atlassian.net/browse/OH-35)**
[OH-35]: https://helsinkisolutionoffice.atlassian.net/browse/OH-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build: pipeline upgrade

public/locales/en/signup.json, public/locales/fi/signup.json, public/locales/sv/signup.json, src/common/components/accordion/Accordion.tsx, src/domain/event/__tests__/query.test.ts, src/domain/event/constants.ts, src/domain/event/hooks/useEventWithSubEventsData.ts, src/domain/event/query.ts, src/domain/event/types.ts, src/domain/event/utils.ts, src/domain/signupGroup/eventInfo/EventInfo.tsx, src/domain/signupGroup/eventInfo/EventTimes.tsx, src/domain/signupGroup/eventInfo/__tests__/EventTimes.test.tsx, src/domain/signupGroup/eventInfo/eventInfo.module.scss, src/domain/signupGroup/summaryPage/summaryEventInfo/SummaryEventInfo.tsx
Display event times for recurring event in a signup form
[LINK-1884](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1884)
[LINK-1884]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1884 | Add event times to signup form

public/locales/en/paymentCancelled.json, public/locales/en/paymentCompleted.json, public/locales/fi/paymentCancelled.json, public/locales/fi/paymentCompleted.json, public/locales/sv/paymentCancelled.json, public/locales/sv/paymentCompleted.json, src/__tests__/Pages.test.tsx, src/domain/app/routes/constants.ts, src/domain/payment/PaymentCancelledPage.tsx, src/domain/payment/PaymentCompletedPage.tsx, src/domain/payment/__tests__/PaymentCancelledPage.test.tsx, src/domain/payment/__tests__/PaymentCompletedPage.test.tsx, src/pages/payment/cancelled/index.tsx, src/pages/payment/completed/index.tsx, src/tests/initI18n.ts, src/types.ts, src/utils/generateGetServerSideProps.ts, src/utils/getServerSideTranslations.ts
Generic payment completed and payment cancelled pages
[LINK-1044](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1044)
[LINK-1044]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1044 | generic payment pages

public/locales/en/common.json, public/locales/fi/common.json, public/locales/sv/common.json, src/common/components/accessibilityNotificationContext/AccessibilityNotificationContext.tsx, src/common/components/accessibilityNotificationContext/accessibilityNotification.module.scss, src/common/components/accessibilityNotificationContext/hooks/useAccessibilityNotificationContext.tsx, src/common/components/searchInput/SearchInput.tsx, src/common/components/searchInput/__tests__/SearchInput.test.tsx, src/common/components/searchStatus/SearchStatus.tsx, src/domain/attendanceList/attendeeList/AttendeeList.tsx, src/domain/attendanceList/searchRow/__tests__/__snapshots__/SearchRow.test.tsx.snap, src/domain/singups/__mocks__/testUtils.ts, src/domain/singups/searchPanel/__tests__/SearchPanel.test.tsx, src/pages/_app.tsx, src/utils/testUtils.tsx
- SearchInput component is meant to be used in the cases that suggestion list is needed. Use TextInput component instead to improve accessibility and to avoid unnecessary and misleading alerts
- Add a div element which contains search results count after search to improve accessibility for screen reader users
[LINK-1769](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1769)
[LINK-1769]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1769 | Search related accessibility improvements

src/common/components/formFields/SingleSelectField.tsx, src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx, src/domain/signupGroup/__tests__/validation.test.ts, src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx, src/domain/signupGroup/validation.ts
Change the native language field to optional
[LINK-1978](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1978)
[LINK-1978]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1978 | Change the native language field to optional

public/locales/en/common.json, public/locales/fi/common.json, public/locales/sv/common.json, src/common/components/formFields/CheckboxGroupField.tsx, src/common/components/formFields/__tests__/CheckboxGroupField.test.tsx
- Display accessibility notification after showing more or hiding options in checkbox group
[LINK-1761](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1761)
[LINK-1761]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1761 | Improve accessibility of checkbox group

public/locales/en/reservation.json, public/locales/en/signup.json, public/locales/fi/reservation.json, public/locales/fi/signup.json, public/locales/sv/reservation.json, public/locales/sv/signup.json, src/domain/signup/constants.ts, src/domain/signupGroup/modals/reservationTimeExpiringModal/ReservationTimeExpiringModal.tsx, src/domain/signupGroup/reservationTimer/ReservationTimer.tsx, src/domain/signupGroup/reservationTimer/__tests__/ReservationTimer.test.tsx
- Display accessibility notification after loading reservation timer. Text tells to user how much time there is to register.
- Display modal if registration time is expiring soon
[LINK-1754](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1754)
[LINK-1754]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-1754 | Modal before reservation time is expiring

src/domain/event/__tests__/utils.test.ts, src/domain/event/eventCalendarButton/EventCalendarButton.tsx, src/domain/event/eventCalendarButton/__tests__/EventCalendarButton.test.tsx, src/domain/event/utils.ts
Add all sub-events to an ics file if super event type of the event is recurring event
[LINK-2003](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2003)
[LINK-2003]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add all sub events to the ics file

src/domain/signupGroup/summaryPage/SummaryPage.tsx, src/domain/signupGroup/summaryPage/__tests__/SummaryPage.test.tsx
Clear session storage before moving to Talpa
[LINK-2075](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2075)
[LINK-2075]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-2075 | Clear session storage before moving to Talpa

src/domain/signup/EditSignupPage.tsx, src/domain/signup/__tests__/utils.test.ts, src/domain/signup/types.ts, src/domain/signup/utils.ts, src/domain/signupGroup/__tests__/utils.test.ts, src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx, src/domain/signupGroup/types.ts, src/domain/signupGroup/utils.ts, src/utils/mockDataUtils.ts
Prevent to edit/delete if there is payment cancellation/refund
[LINK-2089](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2089)
[LINK-2089]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINK-2089 | prevent to edit/delete if there is payment cancellation/refund

src/domain/app/sentry/utils.ts
Sentry should clean normalized data.
**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**
=> fix: sentry clean normalized data LINK-2186

src/pages/_app.tsx, src/styles/main.scss, src/styles/vendor/normalize.scss
- Normalize font-sizes to help with scaling when users changes font-size on device
- Set meta viewport
**[LINK-2149](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2149):**
[LINK-2149]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: normalize font sizes LINK-2149

public/locales/en/signup.json, public/locales/fi/signup.json, public/locales/sv/signup.json, src/domain/signupGroup/participantAmountSelector/ParticipantAmountSelector.tsx, src/domain/signupGroup/participantAmountSelector/participantAmountSelector.module.scss
Added an addendum for participant selector to remind users to click update button when increasing or decreasing participant count.
**[LINK-2211)](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2211):**
=> fix: added addendum for participant amount selector

public/locales/en/signup.json, public/locales/fi/signup.json, public/locales/sv/signup.json, src/domain/signupGroup/participantAmountSelector/__tests__/ParticipantAmountSelector.test.tsx, src/domain/signupGroup/participantAmountSelector/participantAmountSelector.module.scss, src/domain/signupGroup/reservationTimer/ReservationTimer.tsx, src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx, src/domain/signupGroup/signupGroupForm/availableSeatsText/AvailableSeatsText.tsx, src/domain/signupGroup/signupGroupForm/signupGroupForm.module.scss, src/domain/signupGroup/testUtils.ts
Changes to how reservation timer and participants selector are presented to the user.
**[LINK-2212](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2212):**
[LINK-2212]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: partifipant selector text and styling changes LINK-2212

src/domain/event/eventCalendarButton/EventCalendarButton.tsx, src/domain/signup/modals/confirmDeleteSignupModal/ConfirmDeleteSignupModal.tsx, src/domain/signupGroup/editButtonPanel/EditButtonPanel.tsx, src/domain/signupGroup/modals/confirmDeleteSignupFromFormModal/ConfirmDeleteSignupFromFormModal.tsx, src/domain/signupGroup/summaryPage/SummaryPage.tsx
Fixes to button variants that were migrated incorrectly.
**[LINK-2152](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2152):**
[LINK-2152]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: button variant fixes LINK-2152
