- public/locales/en/common.json
- public/locales/en/enrolment.json
- public/locales/fi/common.json
- public/locales/fi/enrolment.json
- public/locales/sv/common.json
- public/locales/sv/enrolment.json
- src/common/components/cancelledTempale/CancelledTemplate.tsx
- src/common/components/cancelledTempale/cancelledTemplate.module.scss
- src/common/components/formFields/DateInputField.tsx
- src/domain/app/routes/constants.ts
- src/domain/enrolment/EditEnrolmentPage.tsx
- src/domain/enrolment/EnrolmentCancelledPage.tsx
- src/domain/enrolment/__mocks__/enrolment.ts
- src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx
- src/domain/enrolment/__tests__/EnrolmentCancelledPage.test.tsx
- src/domain/enrolment/__tests__/utils.test.ts
- src/domain/enrolment/constants.ts
- src/domain/enrolment/editEnrolmentPageMeta/EditEnrolmentPageMeta.tsx
- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/modals/ConfirmCancelModal.tsx
- src/domain/enrolment/modals/modals.module.scss
- src/domain/enrolment/mutation.ts
- src/domain/enrolment/utils.ts
- src/hooks/useIsMounted.ts
- src/hooks/useMountedState.ts
- src/pages/registration/[registrationId]/enrolment/[enrolmentId]/edit/[accessCode]/index.tsx
- src/pages/registration/[registrationId]/enrolment/cancelled/index.tsx
Read-only view of enrolment form
Edit enrolment page with cancel enrolment button
Enrolment cancelled page
[LINK-684](https://helsinkisolutionoffice.atlassian.net/browse/LINK-684)
Create new enrolment from page http://localhost:3000/fi/registration/13/enrolment/create
Go to edit enrolment page by changing e.g. http://localhost:3000/fi/registration/13/enrolment/39/completed/477309ee-a7d6-4730-94f1-c70f6f2fbd26 http://localhost:3000/fi/registration/13/enrolment/39/edit/477309ee-a7d6-4730-94f1-c70f6f2fbd26
> LINK-684 | Cancelling enrolment

- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
Bump actions/checkout@v2 to actions/checkout@v3 to fix GitHub action deprecation warnings
[LINK-1157](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1157)
[LINK-1157]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Latest GitHub action run can be found at https://github.com/City-of-Helsinki/linkedregistrations-ui/actions/runs/4145212175
> LINK-1157 | Update actions/checkout to latest versions to fix deprecation warnings

- public/locales/en/enrolment.json
- public/locales/fi/enrolment.json
- public/locales/sv/enrolment.json
- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/enrolmentForm/availableSeatsText/AvailableSeatsText.tsx
- src/domain/enrolment/enrolmentForm/availableSeatsText/__tests__/AvailableSeatsText.test.tsx
- src/domain/enrolment/registrationWarning/RegistrationWarning.tsx
- src/domain/enrolment/registrationWarning/__tests__/RegistrationWarning.test.tsx
- src/domain/registration/__mocks__/registration.ts
- src/domain/registration/__tests__/utils.test.ts
- src/domain/registration/utils.ts
- src/utils/mockDataUtils.ts
- Enrolment is closed if enrolment_start_time is defined and is in the future or enrolment_end_time is defined and is in the past
- Show different warning message if enrolment is open but there is no available seats
- Add reserved seats to available seats amount if there is already reservation in the session storage
- Disable enrolment form also if there is no available places and seats reservation is not stored to session storage
PR for API implementation: https://github.com/City-of-Helsinki/linkedevents/pull/611
PR for Linked Components UI: https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/188
[LINK-1363](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1363)
[LINK-1363]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
> LINK-1363 | Prevent to reserve seats or signup is enrolment is not open

- src/utils/__tests__/validationUtils.test.ts
- src/utils/validationUtils.ts
Improve phone number validation to allow e.g. +358 44 1234 567 which is used as placeholder text
[LINK-1530](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1530)
[LINK-1530]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1530 | Improve phone number validation

- package.json
- src/domain/app/cookieConsent/CookieConsent.tsx
- yarn.lock
Define domain for the cookie consent modal cookies. Reason for this is that https://www.hel.fi/fi clear all the cookies that it's not using. So visiting in that site also cleared cookies from Linked Registration UI
[LINK-1482](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1482)
[LINK-1482]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1482 | Define domain for the cookie consent modal cookies

- public/locales/en/enrolment.json
- public/locales/fi/enrolment.json
- public/locales/sv/enrolment.json
- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
Rename Privacy policy as Data protection notice
[LINK-1440](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1440)
[LINK-1440]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1440 | Rename Privacy policy as Data protection notice

- public/locales/en/signup.json
- public/locales/fi/signup.json
- public/locales/sv/signup.json
- src/domain/signup/EditSignupPage.tsx
- src/domain/signup/__mocks__/signup.ts
- src/domain/signup/__tests__/EditSignupPage.test.tsx
- src/domain/signup/utils.ts
- src/domain/signupGroup/CreateSignupGroupPage.tsx
- src/domain/signupGroup/EditSignupGroupPage.tsx
- src/domain/signupGroup/__mocks__/signupGroup.ts
- src/domain/signupGroup/__tests__/EditSignupGroupPage.test.tsx
- src/domain/signupGroup/constants.ts
- src/domain/signupGroup/editButtonPanel/EditButtonPanel.tsx
- src/domain/signupGroup/mutation.ts
- src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
- src/domain/signupGroup/signupGroupForm/signups/Signups.tsx
- src/domain/signupGroup/signupGroupForm/signups/signup/Signup.tsx
- src/domain/signupGroup/signupGroupForm/signups/signup/signup.module.scss
- src/domain/signupGroup/summaryPage/SummaryPage.tsx
- src/domain/signupGroup/testUtils.ts
- src/domain/signupGroup/types.ts
- src/domain/signupGroup/utils.ts
- src/styles/main.scss
- src/styles/mixins.scss
Changes in UI components to support updating signup or signup group
This is one of the 5 PRs that replaced https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/74. The purpose of these PRs is to implement pages to update signups and signup groups
PR Parts:
- Replace LoadingButton component with HDS Button (https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/81)
- Move signup form test util functions to separate file (https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/82)
- Move delete signup button to the page bottom (https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/83)
- Util functions and queries to update signups and signups groups (https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/84)
- **Changes in UI components to …
> LINK-1484 |  5/5 Changes in UI components to support updating signup or signup group

- src/domain/signupGroup/hooks/useNotificationOptions.ts
- src/domain/signupGroup/testUtils.ts
Hide SMS notification options since it's not supported in API
[LINK-1505](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1505)
[LINK-1505]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1505 | Hide SMS notification options since it's not supported in API

- src/domain/signup/EditSignupPage.tsx
- src/domain/signupGroup/CreateSignupGroupPage.tsx
- src/domain/signupGroup/EditSignupGroupPage.tsx
- src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx
- src/domain/signupGroup/participantAmountSelector/ParticipantAmountSelector.tsx
- src/domain/signupGroup/participantAmountSelector/__tests__/ParticipantAmountSelector.test.tsx
- src/domain/signupGroup/reservationTimer/__tests__/ReservationTimer.test.tsx
- src/domain/signupGroup/signupGroupForm/signups/Signups.tsx
- src/domain/signupGroup/signupGroupForm/signups/signup/Signup.tsx
- src/domain/signupGroup/signupGroupFormContext/SignupGroupFormContext.tsx
- src/domain/signupGroup/summaryPage/SummaryPage.tsx
- src/utils/testUtils.tsx
Move participant amount value to SignupGroupFormContext and update it after deleting a signup from the form
[LINK-1619](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1619)
1. Open create signup group page
2. Input at least 2 to the participant amount input and press update button
3. Delete one of the signups
Expected result:
Participant amount input value should be updated to match number of signups in the form
[LINK-1619]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1619 | Update participant amount input value after deleting a signup

- src/__tests__/Pages.test.tsx
- src/domain/app/header/Header.tsx
- src/domain/signup/__tests__/EditSignupPage.test.tsx
- src/domain/signup/__tests__/utils.test.ts
- src/domain/signup/hooks/useSignupActions.ts
- src/domain/signup/utils.ts
- src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx
- src/domain/signupGroup/__tests__/EditSignupGroupPage.test.tsx
- src/domain/signupGroup/__tests__/utils.test.ts
- src/domain/signupGroup/hooks/useSignupGroupActions.ts
- src/domain/signupGroup/reservationTimer/__tests__/ReservationTimer.test.tsx
- src/domain/signupGroup/summaryPage/__tests__/SummaryPage.test.tsx
- src/domain/signupGroup/utils.ts
- src/domain/user/hooks/useUser.ts
- src/hooks/__tests__/useHandleError.test.ts
- src/hooks/useHandleError.ts
- Don't send signup group `extra_info` or signup `date_of_birth`, `email`, `extra_info`, `first_name`, `last_name` or `phone_number` to Sentry,
- Inject username of user instance to each Sentry error report
[LINK-1623](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1623)
[LINK-1623]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1623 | Don't send sensitive data to Sentry

- package.json
- src/common/components/notification/Notification.tsx
- src/common/components/notification/notification.module.scss
- src/common/components/notificationsContext/NotificationsContext.tsx
- src/common/components/notificationsContext/__tests__/NotificationsContext.test.tsx
- src/common/components/notificationsContext/hooks/useNotificationsContext.ts
- src/domain/attendanceList/__tests__/AttendanceListPage.test.tsx
- src/domain/attendanceList/attendeeList/AttendeeList.tsx
- src/domain/signup/__tests__/EditSignupPage.test.tsx
- src/domain/signupGroup/__tests__/EditSignupGroupPage.test.tsx
- src/domain/signupGroup/authenticationRequiredNotification/AuthenticationRequiredNotification.tsx
- src/domain/signupGroup/registrationWarning/RegistrationWarning.tsx
- src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
- src/domain/signupGroup/summaryPage/SummaryPage.tsx
- src/pages/_app.tsx
- src/utils/testUtils.tsx
- yarn.lock
- Add Notification component to common components. Use HDS Notification component as base and add id for it to be able to get it with document.getElementById
- Replace all Notifications with this component
- Implement `NotificationsProvider` component which is used to show multiple Notifications at the same time
- Add `useNotificationsContext` hook to get function to add new notifications to NotificationsContext
- Replace `toast.error` and `toast.success` messages with Notification messages added by `addNotification` function
[LINK-1602](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1602)
[LINK-1602]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1602 | Replace react-toastify with HDS Notifications

- public/locales/en/common.json
- public/locales/en/signup.json
- public/locales/fi/common.json
- public/locales/fi/signup.json
- public/locales/sv/common.json
- public/locales/sv/signup.json
- src/__tests__/Pages.test.tsx
- src/constants.ts
- src/domain/signup/__mocks__/signup.ts
- src/domain/signup/__tests__/utils.test.ts
- src/domain/signup/types.ts
- src/domain/signup/utils.ts
- src/domain/signupGroup/__tests__/utils.test.ts
- src/domain/signupGroup/__tests__/validation.test.ts
- src/domain/signupGroup/constants.ts
- src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
- src/domain/signupGroup/summaryPage/__tests__/SummaryPage.test.tsx
- src/domain/signupGroup/types.ts
- src/domain/signupGroup/utils.ts
- src/domain/signupGroup/validation.ts
- src/utils/mockDataUtils.ts
Save user consent via API when creating a new signup group
Show user consent checkbox also if editing a signup group and any of user_consent is false
[LINK-1674](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1674)
[LINK-1674]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1674 | Save user_consent via API

- public/locales/en/signup.json
- public/locales/fi/signup.json
- public/locales/sv/signup.json
- src/common/components/errorTemplate/ErrorTemplate.tsx
- src/domain/registration/__tests__/utils.test.ts
- src/domain/registration/utils.ts
- src/domain/signupGroup/CreateSignupGroupPage.tsx
- src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx
- src/domain/signupGroup/signupIsEnded/SignupIsEnded.tsx
- src/domain/signupGroup/summaryPage/SummaryPage.tsx
- src/domain/signupGroup/summaryPage/__tests__/SummaryPage.test.tsx
Show "Ilmoittautuminen tapahtumaan on päättynyt" text instead of signup form is enrolment is already closed
[LINK-1607](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1607)
[LINK-1607]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1607 | Don't show signup form if signup is already closed

- .env
- .gitignore
- next.config.js
- package.json
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- yarn.lock
Sentry’s Next.js SDK  versions 7.26.0-7.76.0 has critical security issue, when the tunnelRoute option is enabled. This doesn't effect to current Linked Registration UI, but it's still better to upgrade @sentry/nextjs to version where this vulnerability is fixed
See https://blog.sentry.io/next-js-sdk-security-advisory-cve-2023-46729/
> Upgrade @sentry/nextjs to version 7.80.0

- src/__tests__/Pages.test.tsx
- src/domain/app/routes/constants.ts
- src/domain/signup/SignupCompletedPage.tsx
- src/domain/signup/constants.ts
- src/domain/signup/hooks/useSignupActions.ts
- src/domain/signup/mutation.ts
- src/domain/signup/signupServerErrorsContext/utils.ts
- src/domain/signup/types.ts
- src/domain/signup/utils.ts
- src/domain/signupGroup/SignupGroupCompletedPage.tsx
- src/domain/signupGroup/__tests__/EditSignupGroupPage.test.tsx
- src/domain/signupGroup/editButtonPanel/EditButtonPanel.tsx
- src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
- src/domain/signupGroup/summaryPage/SummaryPage.tsx
- src/domain/signupGroup/summaryPage/__tests__/SummaryPage.test.tsx
- src/domain/signupGroup/utils.ts
- src/domain/singups/signupsTable/__tests__/SignupsTable.test.tsx
- src/pages/registration/[registrationId]/signup/[signupId]/completed/index.tsx
- Use signup bulk create endpoint to create a signup without group when only 1 signup is added to create signup form
- Redirect user to signup completed page after creating a signup
[LINK-1719](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1719)
[LINK-1719]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1719 | Use signup endpoint when creating a signup

- next-i18next.config.js
- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/__tests__/NextAuth.test.ts
- src/__tests__/Pages.test.tsx
- src/common/components/errorPageWithLogoutButton/ErrorPageWithLogoutButton.tsx
- src/common/components/errorPageWithLogoutButton/errorPageWithLogoutButton.module.scss
- src/common/components/errorPageWithLogoutButton/testUtils.ts
- src/constants.ts
- src/domain/app/header/Header.tsx
- src/domain/app/header/__tests__/Header.test.tsx
- src/domain/app/routes/constants.ts
- src/domain/insufficientPermissions/InsufficientPermissions.tsx
- src/domain/insufficientPermissions/__tests__/InsufficientPermissions.test.tsx
- src/domain/logout/LogoutPage.tsx
- src/domain/logout/__tests__/LogoutPage.test.tsx
- src/domain/strongIdentificationRequired/StrongIdentificationRequired.tsx
- src/domain/strongIdentificationRequired/__tests__/StrongIdentificationRequired.test.tsx
- src/domain/strongIdentificationRequired/strongIdentificationRequired.module.scss
- src/hooks/useSignOut.ts
- src/pages/api/auth/[...nextauth].ts
- src/pages/logout.tsx
Redirect user to Tunnistamo `end_session_endpoint` endpoint after sign out
[LINK-1738](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1738)
[LINK-1738]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1738 | Logout from Tunnistamo after signout

- public/locales/en/signup.json
- public/locales/fi/signup.json
- public/locales/sv/signup.json
- src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
- src/domain/signupGroup/signupGroupForm/signups/signup/Signup.tsx
- src/domain/signupGroup/summaryPage/SummaryPage.tsx
- src/domain/signupGroup/testUtils.ts
Add helper text for signup extra info field and notification for contact person section
Update user consent text
[LINK-1715](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1715)
[LINK-1715]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1715 | Info texts to signup form

- src/domain/signupGroup/__tests__/validation.test.ts
- src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
- src/domain/signupGroup/validation.ts
API doesn't support mandatory fields validation for contact person fields so remove it here as well
[LINK-1777](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1777)
[LINK-1777]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1777 | Remove mandatory fields validation from contact person fields

- README.md
New django-heluser library requires that the client for logging into Django admin has a non-url client id.
Also sync instructions with linkedcomponents-ui
> LINK-1790 | Update instructions for creating working Tunnistamo clients

- src/domain/registration/constants.tsx
- src/domain/registration/types.ts
- src/domain/registration/utils.ts
- src/utils/generateGetServerSideProps.ts
- src/utils/prefetchRegistrationAndEvent.ts
Request only data that is needed for meta data in the server side
- Don’t request user from LE API 
- Drop location from include param value because event place is not used by the meta data
- Drop nocache=true from registration params to get registration from cache if possible
[LINK-1823](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1823)
[LINK-1823]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1823 | Improve performance on server side

- public/locales/en/signup.json
- public/locales/fi/signup.json
- public/locales/sv/signup.json
- src/constants.ts
- src/domain/registration/__tests__/utils.test.ts
- src/domain/registration/utils.ts
- src/domain/signupGroup/CreateSignupGroupPage.tsx
Display enrolment start time when registration is closed
[LINK-1820](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1820)
[LINK-1820]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1820 | Display enrolment start time when registration is closed

- src/common/components/formFields/SingleSelectField.tsx
- Android devices freezes totally when trying to change value of a SingleSelectComponent. Add a short timeout to prevent infinite loop after calling onChange.
[LINK-1853](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1853)
[LINK-1853]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1853 | Add timeout to SingleSelectComponent value change

- src/common/components/formikPersist/FormikPersist.tsx
- src/pages/_app.tsx
- src/pages/api/auth/[...nextauth].ts
- Currently next-auth session refresh interval is 5 minutes. However, the expiration time for the api token is 5 minutes as well. So the api token is getting old before the api token is refreshed. Also refresh api token 60 seconds before expiration time.
- Getting session by using getSession functions sends request to server every time that form state is saved. It's redundant to check session state here anyway so remove the check totally
[LINK-1878](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1878)
[LINK-1878]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1878 | Fix JWT verification failed error

- src/domain/language/hooks/__tests__/useLanguageOptions.test.tsx
- src/domain/language/utils.ts
Prioritise most used languages in the Native language and Service language dropdown in the signup form
[LINK-1848](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1848)
[LINK-1848]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  LINK-1848 | prioritise most used language options

- src/domain/signupGroup/summaryPage/SummaryPage.tsx
Use checkout url which contains user id when moving to Talpa payment to avoid issues when user is authenticated with Helsinki-tunnus
> fix: use checkout url with user info

- .commitlintrc.json
- .github/workflows/ci.yml
- .husky/commit-msg
- README.md
- package.json
- yarn.lock
Add commit lint to the project
[LINK-1961](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1961)
[LINK-1961]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-1961 | add commit lint to the project

- src/__tests__/NextAuth.test.ts
- src/domain/signupGroup/reservationTimer/ReservationTimer.tsx
- src/pages/api/auth/[...nextauth].ts
Having undefined values in user data causes server errors when trying to serialise it. Fix the issue by replacing undefined values with null.
getSession function was executed every second in ReservationTimer component. Fix this by removing getSession function call from useEffect
> fix: replace undefined with null in user data

- public/locales/en/signup.json
- public/locales/fi/signup.json
- public/locales/sv/signup.json
- src/domain/event/__mocks__/event.ts
- src/domain/event/__tests__/utils.test.ts
- src/domain/event/utils.ts
- src/domain/registration/__mocks__/registration.ts
- src/domain/signup/__tests__/EditSignupPage.test.tsx
- src/domain/signup/__tests__/utils.test.ts
- src/domain/signup/utils.ts
- src/domain/signupGroup/__tests__/EditSignupGroupPage.test.tsx
- src/domain/signupGroup/__tests__/utils.test.ts
- src/domain/signupGroup/editButtonPanel/EditButtonPanel.tsx
- src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
- src/domain/signupGroup/utils.ts
Prevent to delete a signup or a signup group after an event has started.
[LINK-2104](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2104)
[LINK-2104]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LINK-2104 | Prevent to delete signup after event start_time

- src/domain/app/sentry/utils.ts
JS objects may contain circular references which leads to stack overflow unless there is a max recursion depth defined.
refs: LINK-2171
> fix: add MAX_CLEAN_DEPTH=3 to cleanSensitiveData

- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- src/domain/app/sentry/utils.ts
cleanSensitiveData depth check causes unwanted behaviour in signup. Replacing with [ExtraErrorData integration](https://docs.sentry.io/platforms/javascript/configuration/integrations/extraerrordata/) with depth set to 3.
**[LINK-2186](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2186):**
[LINK-2186]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: sentry add extra error data integration LINK-2186

- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
Add missing clear button aria-label to signup language select.
**[LINK-2154](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2154):**
[LINK-2154]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: a11y signup language aria-label LINK-2154

- src/common/components/buttonPanel/buttonPanel.module.scss
Make buttonPanel non sticky so that SR focus cannot get hidden behind it.
**[LINK-2148](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2148):**
[LINK-2148]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: a11y make buttonPanel non sticky LINK-2148

- src/domain/signupGroup/instructions/Instructions.tsx
- src/domain/signupGroup/instructions/instructions.module.scss
- src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
- src/domain/signupGroup/signupGroupForm/signupGroupForm.module.scss
- src/domain/signupGroup/signupGroupForm/signups/signup/Signup.tsx
- src/domain/signupGroup/summaryPage/contactPersonInfo/ContactPersonInfo.tsx
Fixing signup form heading levels.
**[LINK-2150](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2150)**
**[LINK-2157](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2157)**
[LINK-2150]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-2157]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: a11y heading levels LINK-2150 LINK-2157

- src/common/components/formFields/CheckboxField.tsx
Fixing user consent error message is not linked to field.
**[LINK-2155](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2155):**
[LINK-2155]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: a11y checkboxField error message LINK-2155

- src/domain/signupGroup/summaryPage/summaryEventInfo/SummaryEventInfo.tsx
Should set focus on heading when navigating to signup summary.
**[LINK-2156](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2156):**
[LINK-2156]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: signup summary focus on heading LINK-2156

- src/domain/signup/signupServerErrorsContext/__tests__/utils.test.ts
- src/domain/signup/signupServerErrorsContext/utils.ts
When adding multiple signups, only errors for the first one are currently displayed. Fixing so that errors for all persons are listed. Also making use of all the label translations available that can be then displayed in the error message.
**[LINK-2158](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2158):**
[LINK-2158]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: error handling enhancements LINK-2158

- .gitignore
- next-env.d.ts
- public/locales/en/signup.json
- public/locales/fi/signup.json
- public/locales/sv/signup.json
- src/domain/signupGroup/SignupGroupCompletedPage.tsx
Added suggestion to take a screencapture after registration to event.
**[LINK-2195](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2195):**
[LINK-2195]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: added screen capture suggestion after registration

- package.json
- yarn.lock
Upgrade @sentry/nextjs to 7.12.3. This solves vulnerability: https://github.com/City-of-Helsinki/linkedregistrations-ui/security/dependabot/50
**[LINK-2191](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2191):**
[LINK-2191]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> deps: upgrade @sentry/nextjs to 7.120.3 LINK-2191

- public/locales/en/common.json
- public/locales/fi/common.json
- public/locales/sv/common.json
- src/__tests__/Pages.test.tsx
- src/domain/app/footer/Footer.tsx
- src/domain/app/footer/footer.module.scss
- src/domain/app/layout/pageLayout/PageLayout.tsx
- src/domain/app/layout/pageLayout/pageLayout.module.scss
- src/domain/app/routes/constants.ts
- src/pages/cookies/index.tsx
Users should be able to change consent settings. Added simple footer and cookies page.
**[LINK-1759](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1759):**
<br><br>
[LINK-1759]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add cookies page LINK-2152
